# Generated by Django 5.1.5 on 2025-03-15 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=200)),
                ('instructions', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='item_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplexItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='borrow.item')),
                ('condition', models.CharField(max_length=200)),
            ],
            bases=('borrow.item',),
        ),
        migrations.CreateModel(
            name='SimpleItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='borrow.item')),
            ],
            bases=('borrow.item',),
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('patron_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='borrow.patron')),
                ('can_add_items', models.BooleanField(default=True)),
            ],
            bases=('borrow.patron',),
        ),
        migrations.CreateModel(
            name='BorrowedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('due_date', models.DateTimeField()),
                ('returned', models.BooleanField(default=False)),
                ('item_type', models.CharField(choices=[('SIMPLE', 'Simple Item'), ('COMPLEX', 'Complex Item')], max_length=7)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow.item')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow.patron')),
            ],
        ),
    ]
