# Generated by Django 5.1.5 on 2025-02-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='location',
            field=models.CharField(default='Slaughter', max_length=200),
            preserve_default=False,
        ),
    ]
