# Generated by Django 5.1.5 on 2025-03-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='items_list',
            field=models.ManyToManyField(blank=True, related_name='collections', to='borrow.item'),
        ),
    ]
