# Generated by Django 5.1.5 on 2025-03-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_alter_collections_items_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='For private collections, only these patrons (librarians are automatically granted permission) can see and borrow items.', to='borrow.patron'),
        ),
    ]
