# Generated by Django 5.1.5 on 2025-03-31 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_alter_collections_items_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow.patron')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow.item')),
            ],
        ),
    ]
