# Generated by Django 5.1.5 on 2025-04-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0004_alter_collections_allowed_users'),
        ('borrow', '0005_borrowrequest_status'),
    ]

    operations = [
    ]
