# Generated by Django 5.1.5 on 2025-04-14 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0005_collections_created_at'),
        ('borrow', '0006_merge_20250401_1032'),
    ]

    operations = [
    ]
