# Generated by Django 5.1.5 on 2025-04-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('BALLS', 'Balls / Frisbees'), ('STICKS', 'Sticks / Rackets'), ('NETS', 'Nets / Goals'), ('OTHER', 'Other Sporting Equipment')], default='OTHER', help_text='Used for grouping in browse and picking the right form', max_length=10),
        ),
    ]
