# Generated by Django 5.1.5 on 2025-04-24 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0009_collectionrequest'),
        ('borrow', '0009_item_category'),
    ]

    operations = [
    ]
