# Generated by Django 5.1.5 on 2025-04-25 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0010_merge_0009_collectionrequest_0009_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 16, 40, 30, 192703, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
