# Generated by Django 5.1.5 on 2025-04-27 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0010_merge_0009_collectionrequest_0009_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='items_list',
        ),
        migrations.CreateModel(
            name='CollectionItemAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_quantity', models.IntegerField(default=1, help_text='Number of units allocated to this collection')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_allocations', to='borrow.collections')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_allocations', to='borrow.item')),
            ],
            options={
                'unique_together': {('collection', 'item')},
            },
        ),
    ]
