# Generated by Django 5.1.5 on 2025-04-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0010_merge_0009_collectionrequest_0009_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='days_to_return',
            field=models.IntegerField(default=7),
        ),
    ]
