# Generated by Django 5.1.5 on 2025-04-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0011_item_days_to_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
