# Generated by Django 5.1.5 on 2025-04-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0012_alter_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexitem',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='OTHER', max_length=10),
        ),
    ]
