# Generated by Django 5.1.5 on 2025-04-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0014_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
